---
version: 2
signalingservers:
- ws://10.20.30.66:8000/ws/device/test/
platforms:
  right_heel:
    stdaddr: 0x01
    bus: can0
    actuators:
    - lower: [-57.5, 48, 25]
      upper: [-38.6, 46, 285]
      min: 260
    - lower: [0, -75, 25]
      upper: [0, -60, 285]
      min: 260
    - lower: [57.5, 48, 25]
      upper: [38.6, 46, 285]
      min: 260

#sensors:
#  left_heel:
#    address: 0x15
#    mode: 2
#    registry: 1
#    mirror: y
#    rows: 12
#    cols: 12
#    zerovalue: 0
#    halfvalue: 2047
#    fullvalue: 4095
#  left_mtp:
#    address: 0x16
#    mode: 1
#    registry: 1
#    mirror: y
#    rows: 10
#    cols: 16
#    zerovalue: 0
#    halfvalue: 2047
#    fullvalue: 4095
#  left_hallux:
#    address: 0x16
#    mode: 1
#    registry: 2
#    mirror: y
#    rows: 12
#    cols: 6
#    zerovalue: 0
#    halfvalue: 2047
#    fullvalue: 4095
#
#  right_heel:
#    address: 0x25
#    mode: 2
#    registry: 1
#    mirror: n
#    rows: 12
#    cols: 12
#    zerovalue: 0
#    halfvalue: 2047
#    fullvalue: 4095
#  right_mtp:
#    address: 0x26
#    mode: 1
#    registry: 1
#    mirror: n
#    rows: 10
#    cols: 16
#    zerovalue: 0
#    halfvalue: 2047
#    fullvalue: 4095
#  right_hallux:
#    address: 0x26
#    mode: 1
#    registry: 2
#    mirror: n
#    rows: 12
#    cols: 6
#    zerovalue: 0
#    halfvalue: 2047
#    fullvalue: 4095
